### ISSUE TITLE
gulp-notify: [Error Running Nunjucks] Error: unknown block tag: blah

### ISSUE THREAD

**Issue by jitendravyas** [zellwk/source-for-automating-workflow-book#1]
https://github.com/zellwk/source-for-automating-workflow-book/blob/master/app/pages/index.nunjucks#L8

**Comment by zellwk** [comment]
This was to force an error with the code when testing. I've yet to correct it in the repo

Stay Awesome!  Zell

**Comment by jitendravyas** [comment]
ok :-)
